---
- hosts: prod
  remote_user: ec2-user

  tasks:
  - name: install htop
    sudo: yes
    apt:
      name: htop
      state: latest

  - name: Installing docker
    sudo: yes
    shell: >
      wget -qO- https://get.docker.com/ | sh
    args:
      creates: /usr/bin/docker

  - user: name=ec2-user groups=docker append=yes
    sudo: yes

