---
- hosts: web
  vars_files:
    - ./../vars.yml
  ## FIX ME - {{web_user}} no workie
  remote_user: ec2-user

  gather_facts: false
  tasks:
  - name: Setup Project Folder
    file: path={{project_root}} state=directory
  - copy: src=./../files/default dest={{project_root}}default owner={{web_user}} group={{web_group}} mode=0644
  - copy: src=./../files/index.html dest={{project_root}}index.html owner={{web_user}} group={{web_group}} mode=0644
  - copy: src=./../files/Dockerfile dest={{project_root}}Dockerfile owner={{web_user}} group={{web_group}} mode=0644
  - name: Docker - build image
    shell: >
      docker build -t nginx .
    args:
      chdir: ~/app

