- hosts: app
  remote_user: {{app_user}}
  vars_files:
    - vars.yml
  gather_facts: false
  tasks:
  - copy: src=./../files/docker-compose.yml dest={{project_root}}docker-compose.yml owner=vagrant group=vagrant mode=0644
  - copy: src=./../files/Dockerfile dest={{project_root}}Dockerfile owner=vagrant group=vagrant mode=0644
  - name: Docker - build image
    shell: >
      docker-compose build
    args:
      chdir: ~/app

