- hosts: app
  vars_files:
    - vars.yml
  remote_user: "{{app_user}}"
  gather_facts: false
  tasks:
  - copy: src=./files/docker-compose.yml dest={{project_root}}docker-compose.yml owner={{app_user}} group={{app_user}} mode=0644
  - copy: src=./files/Dockerfile dest={{project_root}}Dockerfile owner={{app_user}} group={{app_user}} mode=0644
  - name: Docker - build image
    shell: >
      docker-compose build
    args:
      chdir: ~/app

