---
- hosts: app
  vars_files:
    - vars.yml
  remote_user: "{{app_user}}"
  gather_facts: false

  tasks:
  - name: Docker - Run
    shell: >
      docker-compose up -d
    args:
      chdir: "{{project_root}}"
