---
- hosts: app
  vars_files:
    - vars.yml
  remote_user: "{{app_user}}"
  gather_facts: false
  run_once: true

- set_fact: migrate={{ migrate|bool }}
  when: migrate is defined
- set_fact: migrate=false
  when: migrate is not defined

  tasks:
  - { cmd: "bundle exec rake db:migrate", run_once: true, control: migrate }
