---
- hosts: app
  vars_files:
    - vars.yml
  remote_user: "{{app_user}}"
  gather_facts: false

  tasks:
  ## PULL REPO
  - name: Pull sources from the repository.
    git: repo={{project_repo}} dest={{project_root}} version={{branch}} accept_hostkey=true
    sudo_user: "{{app_user}}"

  - name: Migrate
    shell: >
      docker-compose run web bundle install && docker-compose run web bundle exec rake db:create && docker-compose run web bundle exec rake db:migrate
    args:
      chdir: "{{project_root}}"

