---
- hosts: web
  remote_user: ec2-user
  vars_files:
    - vars.yml
  gather_facts: false
  tasks:
  - name: Pull sources from the repository.
    git: repo={{project_repo}} dest={{project_root}} version={{branch}} accept_hostkey=true force=yes
    sudo: yes

